//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChartJsHelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChartJsHelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var ctx = $(&quot;#@CHART_CONTAINER_ID&quot;);
        ///var myChart = new Chart(ctx, {
        ///	type: &apos;line&apos;,
        ///	data: {
        ///		datasets: [@CHART_DATASETS],
        ///		labels: [@VALUE_LABELS]
        ///	},
        ///	options: {
        ///		responsive: true,
        ///		tooltips: {
        ///			mode: &apos;index&apos;,
        ///			intersect: false,
        ///		},
        ///		hover: {
        ///			mode: &apos;nearest&apos;,
        ///			intersect: true
        ///		},
        ///		scales: {
        ///			xAxes: [{
        ///				display: true,
        ///				scaleLabel: {
        ///					display: true,
        ///					labelString: &apos;@TITLE_X&apos;
        ///				}
        ///			}],
        ///			yAxes: [{
        ///				display: true,
        ///				scaleLabel: {
        ///					display [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BarChartScriptTemplate {
            get {
                return ResourceManager.GetString("BarChartScriptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div class=&quot;panel panel-default @CONTAINER_CSS_CLASS&quot;&gt;
        ///	&lt;div class=&quot;panel-heading text-center&quot;&gt;
        ///		&lt;h4&gt;@CHART_TITLE&lt;/h4&gt;
        ///	&lt;/div&gt;
        ///	&lt;div class=&quot;panel-body&quot;&gt;
        ///		&lt;canvas id=&quot;@CHART_CONTAINER_ID&quot; width=&quot;400&quot; height=&quot;400&quot;&gt;&lt;/canvas&gt;
        ///		&lt;script type=&quot;text/javascript&quot;&gt;
        ///			@CHART_JAVASCRIPT
        ///		&lt;/script&gt;
        ///		&lt;div style=&quot;width:100%;text-align:center;&quot;&gt;
        ///			&lt;span&gt;@ADDITIONAL_FOOTER_INFO&lt;/span&gt;
        ///		&lt;/div&gt;
        ///	&lt;/div&gt;
        ///&lt;/div&gt;.
        /// </summary>
        internal static string ChartContainer {
            get {
                return ResourceManager.GetString("ChartContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var ctx = $(&quot;#@CHART_CONTAINER_ID&quot;);
        ///var myChart = new Chart(ctx, {
        ///	type: &apos;doughnut&apos;,
        ///	data: {
        ///		datasets: [{
        ///			data: [@VALUE_POINTS],
        ///			backgroundColor: [@CHART_DATA_COLORS]
        ///		}],
        ///		labels: [@VALUE_LABELS],
        ///	}
        ///});
        ///.
        /// </summary>
        internal static string DoughnutChartScriptTemplate {
            get {
                return ResourceManager.GetString("DoughnutChartScriptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var ctx = $(&quot;#@CHART_CONTAINER_ID&quot;);
        ///var myChart = new Chart(ctx, {
        ///	type: &apos;line&apos;,
        ///	data: {
        ///		datasets: [@CHART_DATASETS],
        ///		labels: [@VALUE_LABELS]
        ///	},
        ///	options: {
        ///		responsive: true,
        ///		tooltips: {
        ///			mode: &apos;index&apos;,
        ///			intersect: false,
        ///		},
        ///		hover: {
        ///			mode: &apos;nearest&apos;,
        ///			intersect: true
        ///		},
        ///		scales: {
        ///			xAxes: [{
        ///				display: true,
        ///				scaleLabel: {
        ///					display: true,
        ///					labelString: &apos;@TITLE_X&apos;
        ///				}
        ///			}],
        ///			yAxes: [{
        ///				display: true,
        ///				scaleLabel: {
        ///					display [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LineChartScriptTemplate {
            get {
                return ResourceManager.GetString("LineChartScriptTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var ctx = $(&quot;#@CHART_CONTAINER_ID&quot;);
        ///var myChart = new Chart(ctx, {
        ///	type: &apos;pie&apos;,
        ///	data: {
        ///		datasets: [{
        ///			data: [@VALUE_POINTS],
        ///			backgroundColor: [@CHART_DATA_COLORS]
        ///		}],
        ///		labels: [@VALUE_LABELS],
        ///	}
        ///});
        ///.
        /// </summary>
        internal static string PieChartScriptTemplate {
            get {
                return ResourceManager.GetString("PieChartScriptTemplate", resourceCulture);
            }
        }
    }
}
